### ISSUE TITLE
consider using Kustomize

### ISSUE THREAD

**Issue by derrickburns** [authelia/chartrepo#126]
Wow.  I have never seen such complicated helm charts, and I have seen quite a few.

I would suggest as an alternative that you consider using Kustomize or jsonnet instead of Helm.

**Comment by james-d-elliott** [comment]
Kustomize is something we had in mind to use in the future, the helm chart is beta at present as clearly documented and has a long way to go before we'll be happy with it.

Would you please elaborate on specific suggestions related to the helm chart? Potentially with some examples, or even a a contribution.

**Comment by derrickburns** [comment]
Frankly, this is less a criticism of your efforts and more an indictment of how poorly matched Helm is to the problem at hand, so please don't take offense.  Helm with go templating is a mismatch for structured objects. 

That said and perhaps ironically, pomerium has a nice chart (at least when I last looked at it).

My favorite solution is jsonnet, but that has small adoption.  Kustomize is ok.

**Comment by james-d-elliott** [comment]
It's my first  chart, basically learning over time. I wouldn't say I was offended at the idea that there are problems with the chart, I already have a number of things in mind that I wish to remove/refactor completely before release. As with anything as you put more time in and get more familiar you figure out what mistakes you made. The only thing that really bothered me was the issue didn't seem helpful or intent on being helpful at face value.

> My favorite solution is jsonnet (see [tanka](https://tanka.dev/install) and [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler)), but that has small adoption. Kustomize is ok. I am seeing more use of it these days.

That unfortunately is my main concern with adopting it. It will potentially take a significant portion of my limited time without people feeling comfortable due to unfamiliarity.

**Comment by derrickburns** [comment]
In any case, I apologize again for the unhelpful comment.  If I had time, I would indeed take a crack at a kustomize solution for you.  Good luck!

**Comment by james-d-elliott** [comment]
Thanks!

**Comment by james-d-elliott** [comment]
Also the input is helpful with the context you provided. :)
