### ISSUE TITLE
Not working in Portainer

### ISSUE THREAD

**Issue by MichelDiz** [authelia/chartrepo#207]
It's a recurring problem in many Charts repos. We were unable to import into Helm via Portainer.

My solution (for other charts) was to make a clone and host it locally via NGINX. But this is not something trivial and friendly.

Cheers.

**Comment by james-d-elliott** [comment]
It's incredibly rude to not include the relevant logs and more information on what you actually did. Show the portainer logs which clearly explain what the issue is and show the actual steps to produce the results.

> It's a recurring problem in many Charts repos.

Sounds like it's a recurring problem with Portainer or your infrastructure in some way. No one else has this issue. Every other solution handles these charts fine. It works with ArgoCD and Flux fine, it works with helm fine.

**Comment by MichelDiz** [comment]
Your perception of what is "rude" is intriguing. 

I also manage responses to users in a large repository. I deal with an equally large community, and I know that logs are very helpful in understanding. But I don't think it is "rude", I think it unhelpful... 

However, the only log that Portainer provides in the case of your repository is:

```
Installation error
"https://charts.authelia.com" is not a valid chart repository or cannot be reached.
```

This doesn't seem to be helpful at all.

What I did was install Portainer and then K3s and incorporate it into Portainer. That's it. With just that, you will be able to reproduce this issue.

It's not a problem with Portainer or my infrastructure, as I mentioned. I created a script to clone these chart repositories and host them locally with NGINX, and it worked perfectly. Something is missing in the hosting of many charts out there, including yours.

My intention was to deploy Authelia with K8s + Traefik + Dgraph with GraphQL Auth and consequently create a tutorial. I'm sure your chart works fine with Helm normally, but not with Portainer. However, I wanted to abstract the use of Helm via CLI.

Again, it's not a problem with Portainer because cloning the repository and serving it via NGINX works perfectly.

Anyway, if you think it is "invalid". You can close it and we are good.

**Comment by james-d-elliott** [comment]
I'm somewhat surprised you wouldn't find it rude if someone were claiming there was an issue with your helm charts if they were fine with the official tools but had issues with a third party [not using](https://github.com/portainer/portainer/blob/develop/pkg/libhelm/go.mod) the [official tooling](https://github.com/helm/helm) without at least doing some simple investigation into the issue and showing that information to help diagnose the potential issue. It's marked as invalid because the information provided was inadequate (and has been removed).

Helm itself seems happy with it as shown by the messages below. Our chart and chart repo is generated by the [official helm release tools](https://github.com/helm/chart-releaser). It does not make a lot of sense that a lot of helm charts have this issue but only with Portainer and that it's *not* an issue with Portainer (especially when official tooling is available in their language and they just decided to make their own), and if it was something missing then surely the failure would not be fixed just by cloning it and hosting it with NGINX. 

In addition here is the [official docs on the chart repo](https://helm.sh/docs/topics/chart_repository/) which as far as I can tell our chart matches exactly in the following ways:
- The index.yaml:
   - Is located at `https://charts.authelia.com/index.yaml` making `https://charts.authelia.com` the correct chart repo path
   - Responds with the content type `text/yaml`
- Uses the official GitHub Pages example with the only exception being on a subdomain
- 


```bash
 helm version
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

```bash
helm repo list
Error: no repositories to show
```
```bash
helm repo add authelia https://charts.authelia.com
"authelia" has been added to your repositories
```

```bash
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "authelia" chart repository
Update Complete. ⎈Happy Helming!⎈
```

```bash
helm search repo authelia
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
authelia/authelia       0.8.57          4.37.5          Authelia is a Single Sign-On Multi-Factor porta...
```

**Comment by MichelDiz** [comment]
Thank you for your response.

To perceive something as "rude", I must assume that the person intends to attack me, either verbally or in their demeanor. Rudeness usually carries a certain tone. I did not have this intention, so if you perceived it that way, I apologize.

I raised my issue with the intention of "alerting" that this problem is occurring. If you don't view Portainer users as significant, you could simply ignore me, right?

From the beginning, I mentioned that this is happening with various self-hosted repositories (which are not part of the official Helm base). In other words, my issue is simply a heads up. If you can't resolve it because the problem lies solely with Portainer, then it's not your issue to deal with. And it is fine.

> issues with a third party not using the official tooling without at least doing some simple investigation into

Well, I don't work in the core code area of these platforms. I wasn't aware that there are numerous ways to support Helm. For me, assuming that Portainer is using the official tools seems like the obvious conclusion. And since I tested it by locally hosting the Chart, it logically follows for me that they must be doing the right thing. After all, I've managed to import and host several other Helm charts myself. Do you see what I mean?

If you're saying the problem is with Portainer, then I apologize. I wasn't able to infer that. Thank you for letting me know. I will reach out to them.

By the way, the cloning trick works. And I used Helm itself to build the container, for example:
```
RUN helm package ./* && helm repo index .
```

Anyway, thanks and sorry for the inconvenience. 

Let's close this since apparently it is something that is not within its scope.

**Comment by james-d-elliott** [comment]
Maybe it's just a misunderstanding. It seemed to me at first that the intention was for us to fix something without any context rather than informational. I do apologize as well since I probably got unnecessarily frustrated.

> Well, I don't work in the core code area of these platforms. I wasn't aware that there are numerous ways to support Helm. For me, assuming that Portainer is using the official tools seems like the obvious conclusion. And since I tested it by locally hosting the Chart, it logically follows for me that they must be doing the right thing. After all, I've managed to import and host several other Helm charts myself. Do you see what I mean?

I can appreciate that. I had no idea they even supported helm. I did a rough investigation to figure out where that error potentially occurs. I couldn't find the specific error myself, but I have since found similar errors from helm itself which may indicate it was fixed in a newer version and potentially they're executing the binary directly rather than using the available tooling. Either way without more helpful log messages (from portainer or helm) there is not much we can do.

I do also see what you mean, and it's very strange that it works in one situation but not others. I think it's probably most strange since you're effectively using the same method we're using to package the chart locally. The only things I can think of to try are network related tests i.e. doing the commands I did locally.
