### ISSUE TITLE
Support Ingress kind with TraefikCRD enabled

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/chartrepo#57]
Basically allow users to revert the ingressroute to an ingress when they desire (cert manager).

**Comment by gtrubach** [comment]
It may be not implemented completely yet but I have a feedback: if `traefikCRD.enabled=true` & `traefikCRD.disableIngressRoute=true` than middleware is referenced on the ingress in the format `<middleware_name>-<namespace>@kubernetescrd` but it should be `<namespace>-<middleware_name>@kubernetescrd`. Otherwise traefik complains that it cannot find the middleware.

**Comment by james-d-elliott** [comment]
Yeah I had implemented it for testing but hadn't gotten around to it, thanks for the information! I'll make that fix today.

**Comment by james-d-elliott** [comment]
This is done.
